/**
 * mockGraphData — static fallback graph for NeuralBrainOrb (DEV / no-API)
 *
 * ~80 nodes across 4 collections, ~110 edges.
 * Shape matches /api/memory/graph response exactly.
 */

import type { GraphNode, GraphEdge } from './NodeDrawer'

/* ── Nodes ──────────────────────────────────────────────────────────────── */

const PEPE: GraphNode[] = [
  { id: 'p01', label: 'summer tote bag design',      collection: 'pepe_memory',     zone: 'etsy',     document: 'Boho-chic tote bag with floral embroidery for summer market.', metadata: {}, connections: 7  },
  { id: 'p02', label: 'boho niche keyword cluster',  collection: 'pepe_memory',     zone: 'etsy',     document: 'Keywords: boho, beach, sunset, aesthetic tote, handmade.', metadata: {}, connections: 9  },
  { id: 'p03', label: 'competitor price scan jul',   collection: 'pepe_memory',     zone: 'etsy',     document: 'Top 10 competitors avg price $28.40. Margin analysis attached.', metadata: {}, connections: 5  },
  { id: 'p04', label: 'floral bundle keywords',      collection: 'pepe_memory',     zone: 'etsy',     document: 'Bundle: wildflower, pressed botanicals, spring wall art.', metadata: {}, connections: 6  },
  { id: 'p05', label: 'pinterest board analysis',    collection: 'pepe_memory',     zone: 'etsy',     document: 'Top pins: pastel minimalism, cottagecore, dried flower frames.', metadata: {}, connections: 8  },
  { id: 'p06', label: 'color theory warm palette',   collection: 'pepe_memory',     zone: 'etsy',     document: 'Analogous warm palette: terracotta + mustard + cream.', metadata: {}, connections: 4  },
  { id: 'p07', label: 'ctr ab test results',         collection: 'pepe_memory',     zone: 'etsy',     document: 'Listing A: 3.2% CTR. Listing B: 4.7% CTR. Winner: photo close-up.', metadata: {}, connections: 3  },
  { id: 'p08', label: 'seasonal trend q3',           collection: 'pepe_memory',     zone: 'etsy',     document: 'Q3 trends: sunflower motifs up 34%, macramé -12%.', metadata: {}, connections: 5  },
  { id: 'p09', label: 'bundle threshold logic',      collection: 'pepe_memory',     zone: 'etsy',     document: 'If cart ≥ 3 items, apply 15% discount automatically.', metadata: {}, connections: 4  },
  { id: 'p10', label: 'shipping cost optimization',  collection: 'pepe_memory',     zone: 'etsy',     document: 'USPS First Class vs Priority: breakeven at 12oz. Use FC below.', metadata: {}, connections: 3  },
  { id: 'p11', label: 'svg color trends 2025',       collection: 'pepe_memory',     zone: 'etsy',     document: 'Neutral earth tones + digital lavender dominate SVG downloads.', metadata: {}, connections: 6  },
  { id: 'p12', label: 'design inspiration session',  collection: 'pepe_memory',     zone: 'etsy',     document: 'Session notes: retro serif + grain texture = premium feel.', metadata: {}, connections: 5  },
  { id: 'p13', label: 'wedding planner niche',       collection: 'pepe_memory',     zone: 'etsy',     document: 'Wedding niche: print-on-demand invites + table seating charts.', metadata: {}, connections: 7  },
  { id: 'p14', label: 'digital art print margins',   collection: 'pepe_memory',     zone: 'etsy',     document: 'Digital download margin: 97%. Physical print: 54% after Printify.', metadata: {}, connections: 4  },
  { id: 'p15', label: 'listing seo revision apr',    collection: 'pepe_memory',     zone: 'etsy',     document: 'Revised 12 listings with long-tail keywords. Views +22% in 7d.', metadata: {}, connections: 5  },
  { id: 'p16', label: 'weekly revenue pattern',      collection: 'pepe_memory',     zone: 'etsy',     document: 'Peak sales: Saturday 10-14h, Sunday 18-22h. Wednesday lowest.', metadata: {}, connections: 3  },
  { id: 'p17', label: 'macro lens product photos',   collection: 'pepe_memory',     zone: 'etsy',     document: 'Macro lens at f/4.5 + lightbox yields best texture detail shots.', metadata: {}, connections: 2  },
  { id: 'p18', label: 'etsy algorithm update may',   collection: 'pepe_memory',     zone: 'etsy',     document: 'Relevancy score now weighs listing age + recent conversion.', metadata: {}, connections: 4  },
  { id: 'p19', label: 'mockup style consistency',    collection: 'pepe_memory',     zone: 'etsy',     document: 'All mockups: bright + airy + lifestyle. No dark studio shots.', metadata: {}, connections: 3  },
  { id: 'p20', label: 'tag strategy research',       collection: 'pepe_memory',     zone: 'etsy',     document: 'Use all 13 tags. Mix exact + broad. First tag = primary keyword.', metadata: {}, connections: 2  },
  { id: 'p21', label: 'star seller requirements',    collection: 'pepe_memory',     zone: 'etsy',     document: '95% on-time ship, 4.8+ rating, <24h reply. Currently: 97/4.9/18h.', metadata: {}, connections: 3  },
  { id: 'p22', label: 'holiday prep checklist',      collection: 'pepe_memory',     zone: 'etsy',     document: 'Q4 prep: extend processing time, prep digital downloads, backup pricing.', metadata: {}, connections: 2  },
  { id: 'p23', label: 'abandoned cart recovery',     collection: 'pepe_memory',     zone: 'etsy',     document: 'Etsy offer nudge after 48h: 10% coupon converts 18% of carts.', metadata: {}, connections: 3  },
  { id: 'p24', label: 'printify supplier matrix',    collection: 'pepe_memory',     zone: 'etsy',     document: 'EU: Monster Digital. US: Printify Express. AU: Sensaria.', metadata: {}, connections: 2  },
  { id: 'p25', label: 'niche research farmhouse',    collection: 'pepe_memory',     zone: 'etsy',     document: 'Farmhouse aesthetic: wood signs, shiplap prints, neutral grain.', metadata: {}, connections: 4  },
  { id: 'p26', label: 'font pairing guide',          collection: 'pepe_memory',     zone: 'etsy',     document: 'Header: Playfair Display. Body: Lato. Accent: Sacramento Script.', metadata: {}, connections: 3  },
  { id: 'p27', label: 'review response templates',   collection: 'pepe_memory',     zone: 'etsy',     document: 'Positive: thank + invite back. 3★: empathize + solve. 1★: refund fast.', metadata: {}, connections: 1  },
  { id: 'p28', label: 'conversion funnel audit',     collection: 'pepe_memory',     zone: 'etsy',     document: 'Step drop: 40% leave at photo #3. Fix: move lifestyle shot to #2.', metadata: {}, connections: 4  },
  { id: 'p29', label: 'print quality comparison',    collection: 'pepe_memory',     zone: 'etsy',     document: 'Matte fine art vs lustre: matte wins for botanical prints.', metadata: {}, connections: 2  },
  { id: 'p30', label: 'quarterly growth analysis',   collection: 'pepe_memory',     zone: 'etsy',     document: 'Q1: +18% revenue. Q2: +31%. Q3 forecast: +25% with new digital line.', metadata: {}, connections: 5  },
]

const PERSONAL: GraphNode[] = [
  { id: 'n01', label: 'morning routine context',     collection: 'personal_memory', zone: 'personal', document: '7am: coffee + 20min deep work before email. No screens first 30min.', metadata: {}, connections: 4  },
  { id: 'n02', label: 'research notes cognitive',    collection: 'personal_memory', zone: 'personal', document: 'Pomodoro 45/15 > 25/5 for design work. Context switching costs -40%.', metadata: {}, connections: 3  },
  { id: 'n03', label: 'reading list apr 2025',       collection: 'personal_memory', zone: 'personal', document: 'Books: The E-Myth, Atomic Habits, Die With Zero. Audio: Huberman Lab.', metadata: {}, connections: 2  },
  { id: 'n04', label: 'weekly review template',      collection: 'personal_memory', zone: 'personal', document: 'Sunday 19h: wins, misses, top 3 next week, energy check.', metadata: {}, connections: 3  },
  { id: 'n05', label: 'project deadline tracker',    collection: 'personal_memory', zone: 'personal', document: 'May 10: new collection launch. May 24: tax filing. Jun 1: rebrand audit.', metadata: {}, connections: 4  },
  { id: 'n06', label: 'ai tool evaluation notes',    collection: 'personal_memory', zone: 'personal', document: 'Claude Opus 4: best reasoning. Midjourney v7: commercial output. GPT-4o: coding.', metadata: {}, connections: 5  },
  { id: 'n07', label: 'fitness protocol tracker',    collection: 'personal_memory', zone: 'personal', document: 'Lift M/W/F. Cardio T/Th. Rest Sat. Protein 160g/day target.', metadata: {}, connections: 1  },
  { id: 'n08', label: 'content calendar ideas',      collection: 'personal_memory', zone: 'personal', document: 'TikTok: behind scenes. Instagram: final product. Pinterest: mood boards.', metadata: {}, connections: 3  },
  { id: 'n09', label: 'budget allocation q2',        collection: 'personal_memory', zone: 'personal', document: 'Ads 15%, tools 8%, materials 12%, savings 25%, living 40%.', metadata: {}, connections: 2  },
  { id: 'n10', label: 'brand voice guidelines',      collection: 'personal_memory', zone: 'personal', document: 'Tone: warm, aspirational, honest. Avoid: luxury, exclusive, trendy.', metadata: {}, connections: 4  },
  { id: 'n11', label: 'delegation framework',        collection: 'personal_memory', zone: 'personal', document: 'Tasks under $20/hr value → automate or delegate. Focus: design + strategy.', metadata: {}, connections: 3  },
  { id: 'n12', label: 'customer avatar profile',     collection: 'personal_memory', zone: 'personal', document: 'Female 28-42, home decor enthusiast, Pinterest power user, $45-120 AOV.', metadata: {}, connections: 5  },
  { id: 'n13', label: 'email sequence draft',        collection: 'personal_memory', zone: 'personal', document: 'Welcome → Day 3 bestsellers → Day 7 story → Day 14 discount.', metadata: {}, connections: 3  },
  { id: 'n14', label: 'password vault notes',        collection: 'personal_memory', zone: 'personal', document: 'Use Bitwarden. Master pw 24 chars. 2FA on all critical accounts.', metadata: {}, connections: 1  },
  { id: 'n15', label: 'tax deductions checklist',    collection: 'personal_memory', zone: 'personal', document: 'Home office 18%, internet 100%, tools 100%, camera equipment 80%.', metadata: {}, connections: 2  },
  { id: 'n16', label: 'product photography setup',   collection: 'personal_memory', zone: 'personal', document: 'Sony A6400 + 50mm f1.8. Daylight 10-12h north window. Foam board reflector.', metadata: {}, connections: 3  },
  { id: 'n17', label: 'competitor watch list',       collection: 'personal_memory', zone: 'personal', document: 'Monitor: @paperluxe, @foliostudio, @theprintshop. Track monthly.', metadata: {}, connections: 2  },
  { id: 'n18', label: 'launch checklist template',   collection: 'personal_memory', zone: 'personal', document: '48h pre: listings live. 24h: social posts scheduled. Launch: email blast.', metadata: {}, connections: 3  },
  { id: 'n19', label: 'idea parking lot',            collection: 'personal_memory', zone: 'personal', document: 'Ideas: astrology prints, custom portraits, affirmation cards, planners.', metadata: {}, connections: 2  },
  { id: 'n20', label: 'quarterly goals review',      collection: 'personal_memory', zone: 'personal', document: 'Q2 goal: 500 sales/mo. Current: 387. Gap: 113. Focus: new listing cadence.', metadata: {}, connections: 4  },
]

const SCREEN: GraphNode[] = [
  { id: 's01', label: 'figma session — brand kit',   collection: 'screen_memory',   zone: 'neural',   document: 'Worked on brand kit: logo variants, color tokens, type scale.', metadata: {}, connections: 3  },
  { id: 's02', label: 'chrome tab — etsy analytics', collection: 'screen_memory',   zone: 'neural',   document: 'Etsy stats page: views 1.2k, visits 890, orders 43, conversion 4.8%.', metadata: {}, connections: 2  },
  { id: 's03', label: 'vscode — agent pexi main',    collection: 'screen_memory',   zone: 'neural',   document: 'Editing NeuralBrainOrb.tsx — replacing Three.js with ForceGraph3D.', metadata: {}, connections: 4  },
  { id: 's04', label: 'notion — product roadmap',    collection: 'screen_memory',   zone: 'neural',   document: 'Roadmap: May collections, June restock, July summer sale prep.', metadata: {}, connections: 3  },
  { id: 's05', label: 'midjourney — style ref',      collection: 'screen_memory',   zone: 'neural',   document: 'Generated: cottagecore floral, neutral grain, watercolor botanical x20.', metadata: {}, connections: 4  },
  { id: 's06', label: 'canva — listing graphics',    collection: 'screen_memory',   zone: 'neural',   document: 'Created 6 listing mockups for summer tote collection. Exported 2000px.', metadata: {}, connections: 2  },
  { id: 's07', label: 'slack — team checkin',        collection: 'screen_memory',   zone: 'neural',   document: 'Discussed Q2 KPIs. Freelancer delivery May 8. Review call May 12.', metadata: {}, connections: 1  },
  { id: 's08', label: 'youtube — algorithm video',   collection: 'screen_memory',   zone: 'neural',   document: 'Watched: "Etsy 2025 algorithm decoded" — 3 key takeaways noted.', metadata: {}, connections: 2  },
  { id: 's09', label: 'terminal — deploy log',       collection: 'screen_memory',   zone: 'neural',   document: 'Deployed AgentPeXI v0.9.4. Build 42s. Zero downtime. WS reconnect ok.', metadata: {}, connections: 3  },
  { id: 's10', label: 'email — supplier quote',      collection: 'screen_memory',   zone: 'neural',   document: 'Printify Pro quote: $24.99/mo saves ~$180/mo at current volume.', metadata: {}, connections: 2  },
  { id: 's11', label: 'pinterest — save batch',      collection: 'screen_memory',   zone: 'neural',   document: 'Saved 28 pins: minimalist home decor, beige aesthetic, plant shelves.', metadata: {}, connections: 3  },
  { id: 's12', label: 'chatgpt — copy draft',        collection: 'screen_memory',   zone: 'neural',   document: 'Drafted 5 listing descriptions for botanical print series.', metadata: {}, connections: 2  },
  { id: 's13', label: 'affinity designer — logo',    collection: 'screen_memory',   zone: 'neural',   document: 'Refined leaf monogram logo. Exported SVG + PNG @1x 2x 3x.', metadata: {}, connections: 2  },
  { id: 's14', label: 'google sheets — cost model',  collection: 'screen_memory',   zone: 'neural',   document: 'Built unit economics model. Break-even at 8 units/listing/mo.', metadata: {}, connections: 3  },
  { id: 's15', label: 'lightroom — photo edit',      collection: 'screen_memory',   zone: 'neural',   document: 'Edited 24 product photos. White balance 5400K, clarity +12, texture +8.', metadata: {}, connections: 1  },
  { id: 's16', label: 'trello — sprint board',       collection: 'screen_memory',   zone: 'neural',   document: 'Sprint May: 8 new listings, 3 redesigns, 1 collection revamp.', metadata: {}, connections: 2  },
  { id: 's17', label: 'brave — research tab',        collection: 'screen_memory',   zone: 'neural',   document: 'Researching: AI image licensing, Etsy digital rights, CC0 resources.', metadata: {}, connections: 2  },
  { id: 's18', label: 'zoom — client call notes',    collection: 'screen_memory',   zone: 'neural',   document: 'Client wants custom wedding invitation suite. Budget $350. Timeline 2w.', metadata: {}, connections: 2  },
  { id: 's19', label: 'spotify — focus playlist',    collection: 'screen_memory',   zone: 'neural',   document: 'Played: deep focus, lo-fi beats. Session: 3h12m. 4 tasks completed.', metadata: {}, connections: 0  },
  { id: 's20', label: 'finder — asset folder',       collection: 'screen_memory',   zone: 'neural',   document: 'Reorganized: /assets/2025/Q2/ → by collection. 847 files sorted.', metadata: {}, connections: 1  },
]

const SHARED: GraphNode[] = [
  { id: 'x01', label: 'cross-domain insight: branding', collection: 'shared_memory', zone: 'analytics', document: 'Personal brand voice directly impacts Etsy shop trust. Consistency = 23% more repeat buyers.', metadata: {}, connections: 11 },
  { id: 'x02', label: 'insight: content → sales link',  collection: 'shared_memory', zone: 'analytics', document: 'Pinterest saves correlate with Etsy views +72h delay. Pinterest is top-of-funnel.', metadata: {}, connections: 9  },
  { id: 'x03', label: 'insight: time blocking roi',     collection: 'shared_memory', zone: 'analytics', document: 'Time-blocked deep work sessions yield 3.2x more completed listings vs reactive work.', metadata: {}, connections: 7  },
  { id: 'x04', label: 'insight: ai tools adoption',     collection: 'shared_memory', zone: 'analytics', document: 'Shops using AI for descriptions see 18% higher CTR vs manually written listings.', metadata: {}, connections: 8  },
  { id: 'x05', label: 'insight: seasonal demand fit',   collection: 'shared_memory', zone: 'analytics', document: 'Personal taste in home decor aligns 67% with bestselling product categories.', metadata: {}, connections: 6  },
  { id: 'x06', label: 'insight: screen-to-listing',     collection: 'shared_memory', zone: 'analytics', document: 'OCR capture of design sessions reduces time-to-listing from 4h to 1.5h avg.', metadata: {}, connections: 5  },
  { id: 'x07', label: 'insight: competitor gap matrix', collection: 'shared_memory', zone: 'analytics', document: 'Identified 3 underserved niches: tarot home decor, dark academia, retro travel.', metadata: {}, connections: 8  },
  { id: 'x08', label: 'insight: revenue diversification', collection: 'shared_memory', zone: 'analytics', document: 'Digital + physical mix reduces revenue volatility by 40% vs digital-only.', metadata: {}, connections: 7  },
  { id: 'x09', label: 'insight: customer lifetime value', collection: 'shared_memory', zone: 'analytics', document: 'Customers who receive personal thank-you note reorder 2.4x more within 90d.', metadata: {}, connections: 6  },
  { id: 'x10', label: 'insight: system leverage',       collection: 'shared_memory', zone: 'analytics', document: 'AgentPeXI automation saves ~14h/week. Reinvest in design and strategy.', metadata: {}, connections: 9  },
]

export const MOCK_NODES: GraphNode[] = [...PEPE, ...PERSONAL, ...SCREEN, ...SHARED]

/* ── Edges ──────────────────────────────────────────────────────────────── */

export const MOCK_EDGES: GraphEdge[] = [
  // pepe_memory dense cluster
  { source: 'p01', target: 'p02', weight: 0.91 },
  { source: 'p01', target: 'p06', weight: 0.85 },
  { source: 'p01', target: 'p05', weight: 0.88 },
  { source: 'p02', target: 'p03', weight: 0.80 },
  { source: 'p02', target: 'p04', weight: 0.87 },
  { source: 'p02', target: 'p15', weight: 0.84 },
  { source: 'p02', target: 'p18', weight: 0.76 },
  { source: 'p03', target: 'p08', weight: 0.79 },
  { source: 'p03', target: 'p30', weight: 0.83 },
  { source: 'p04', target: 'p05', weight: 0.92 },
  { source: 'p04', target: 'p13', weight: 0.88 },
  { source: 'p04', target: 'p12', weight: 0.81 },
  { source: 'p05', target: 'p11', weight: 0.86 },
  { source: 'p05', target: 'p12', weight: 0.79 },
  { source: 'p05', target: 'p25', weight: 0.77 },
  { source: 'p06', target: 'p11', weight: 0.83 },
  { source: 'p06', target: 'p12', weight: 0.90 },
  { source: 'p06', target: 'p26', weight: 0.88 },
  { source: 'p07', target: 'p15', weight: 0.78 },
  { source: 'p07', target: 'p28', weight: 0.82 },
  { source: 'p08', target: 'p18', weight: 0.75 },
  { source: 'p08', target: 'p30', weight: 0.80 },
  { source: 'p09', target: 'p03', weight: 0.74 },
  { source: 'p09', target: 'p10', weight: 0.77 },
  { source: 'p09', target: 'p24', weight: 0.73 },
  { source: 'p10', target: 'p24', weight: 0.79 },
  { source: 'p11', target: 'p14', weight: 0.82 },
  { source: 'p12', target: 'p19', weight: 0.76 },
  { source: 'p13', target: 'p28', weight: 0.84 },
  { source: 'p13', target: 'p15', weight: 0.79 },
  { source: 'p14', target: 'p30', weight: 0.85 },
  { source: 'p15', target: 'p18', weight: 0.80 },
  { source: 'p16', target: 'p30', weight: 0.75 },
  { source: 'p16', target: 'p09', weight: 0.72 },
  { source: 'p17', target: 'p19', weight: 0.78 },
  { source: 'p18', target: 'p28', weight: 0.77 },
  { source: 'p20', target: 'p02', weight: 0.86 },
  { source: 'p20', target: 'p15', weight: 0.82 },
  { source: 'p21', target: 'p07', weight: 0.75 },
  { source: 'p22', target: 'p08', weight: 0.73 },
  { source: 'p22', target: 'p10', weight: 0.72 },
  { source: 'p23', target: 'p28', weight: 0.79 },
  { source: 'p25', target: 'p26', weight: 0.84 },
  { source: 'p26', target: 'p12', weight: 0.87 },
  { source: 'p27', target: 'p23', weight: 0.74 },
  { source: 'p28', target: 'p30', weight: 0.83 },
  { source: 'p29', target: 'p17', weight: 0.77 },
  { source: 'p29', target: 'p14', weight: 0.75 },
  // personal_memory cluster
  { source: 'n01', target: 'n02', weight: 0.84 },
  { source: 'n01', target: 'n04', weight: 0.80 },
  { source: 'n02', target: 'n06', weight: 0.82 },
  { source: 'n03', target: 'n06', weight: 0.75 },
  { source: 'n04', target: 'n05', weight: 0.81 },
  { source: 'n04', target: 'n20', weight: 0.79 },
  { source: 'n05', target: 'n18', weight: 0.83 },
  { source: 'n06', target: 'n11', weight: 0.78 },
  { source: 'n08', target: 'n10', weight: 0.82 },
  { source: 'n08', target: 'n13', weight: 0.79 },
  { source: 'n10', target: 'n12', weight: 0.88 },
  { source: 'n10', target: 'n13', weight: 0.84 },
  { source: 'n11', target: 'n09', weight: 0.76 },
  { source: 'n12', target: 'n13', weight: 0.85 },
  { source: 'n12', target: 'n17', weight: 0.77 },
  { source: 'n15', target: 'n09', weight: 0.73 },
  { source: 'n16', target: 'n01', weight: 0.79 },
  { source: 'n18', target: 'n19', weight: 0.75 },
  { source: 'n19', target: 'n08', weight: 0.72 },
  { source: 'n20', target: 'n05', weight: 0.80 },
  // screen_memory cluster
  { source: 's01', target: 's06', weight: 0.83 },
  { source: 's01', target: 's13', weight: 0.87 },
  { source: 's02', target: 's14', weight: 0.79 },
  { source: 's03', target: 's09', weight: 0.85 },
  { source: 's04', target: 's16', weight: 0.80 },
  { source: 's05', target: 's01', weight: 0.86 },
  { source: 's05', target: 's11', weight: 0.82 },
  { source: 's06', target: 's15', weight: 0.78 },
  { source: 's09', target: 's14', weight: 0.76 },
  { source: 's11', target: 's06', weight: 0.79 },
  { source: 's12', target: 's08', weight: 0.74 },
  { source: 's14', target: 's16', weight: 0.77 },
  { source: 's17', target: 's08', weight: 0.73 },
  { source: 's18', target: 's04', weight: 0.75 },
  // cross-collection arcs — shared_memory as hub
  { source: 'x01', target: 'p02', weight: 0.88 },
  { source: 'x01', target: 'n10', weight: 0.85 },
  { source: 'x02', target: 'p05', weight: 0.91 },
  { source: 'x02', target: 's11', weight: 0.84 },
  { source: 'x03', target: 'n01', weight: 0.87 },
  { source: 'x03', target: 'p14', weight: 0.83 },
  { source: 'x04', target: 'n06', weight: 0.90 },
  { source: 'x04', target: 'p15', weight: 0.86 },
  { source: 'x05', target: 'p08', weight: 0.84 },
  { source: 'x05', target: 'n04', weight: 0.80 },
  { source: 'x06', target: 's03', weight: 0.89 },
  { source: 'x06', target: 'p17', weight: 0.82 },
  { source: 'x07', target: 'p03', weight: 0.86 },
  { source: 'x07', target: 'p25', weight: 0.83 },
  { source: 'x07', target: 'n12', weight: 0.79 },
  { source: 'x08', target: 'p14', weight: 0.87 },
  { source: 'x08', target: 'p30', weight: 0.84 },
  { source: 'x09', target: 'n12', weight: 0.88 },
  { source: 'x09', target: 'p27', weight: 0.81 },
  { source: 'x10', target: 's03', weight: 0.93 },
  { source: 'x10', target: 'n11', weight: 0.90 },
  { source: 'x10', target: 'p09', weight: 0.87 },
  // extra cross-collection sparse arcs
  { source: 'p13', target: 'n08', weight: 0.76 },
  { source: 's05', target: 'p06', weight: 0.80 },
  { source: 'n16', target: 's15', weight: 0.83 },
  { source: 's02', target: 'p07', weight: 0.77 },
  { source: 'n20', target: 'p30', weight: 0.81 },
]
