"""initial

Revision ID: 28ec7f4d6562
Revises: 
Create Date: 2026-04-08 12:53:08.467719

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '28ec7f4d6562'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.create_table('leads',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('google_place_id', sa.Text(), nullable=False),
    sa.Column('business_name', sa.Text(), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('city', sa.Text(), nullable=True),
    sa.Column('region', sa.Text(), nullable=True),
    sa.Column('country', sa.Text(), server_default=sa.text("'IT'"), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('google_rating', sa.Numeric(precision=2, scale=1), nullable=True),
    sa.Column('google_review_count', sa.Integer(), nullable=True),
    sa.Column('google_category', sa.Text(), nullable=True),
    sa.Column('website_url', sa.Text(), nullable=True),
    sa.Column('phone', sa.Text(), nullable=True),
    sa.Column('sector', sa.Text(), nullable=False),
    sa.Column('service_gap_detected', sa.Boolean(), server_default=sa.text('FALSE'), nullable=True),
    sa.Column('suggested_service_type', sa.Text(), nullable=True),
    sa.Column('gap_signals', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('lead_score', sa.Integer(), nullable=True),
    sa.Column('qualified', sa.Boolean(), nullable=True),
    sa.Column('disqualify_reason', sa.Text(), nullable=True),
    sa.Column('gap_summary', sa.Text(), nullable=True),
    sa.Column('estimated_value_eur', sa.Integer(), nullable=True),
    sa.Column('vat_number', sa.Text(), nullable=True),
    sa.Column('ateco_code', sa.Text(), nullable=True),
    sa.Column('company_size', sa.Text(), nullable=True),
    sa.Column('social_facebook_url', sa.Text(), nullable=True),
    sa.Column('social_instagram_url', sa.Text(), nullable=True),
    sa.Column('enrichment_confidence', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('enrichment_level', sa.Text(), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    sa.Column('status', sa.Text(), server_default=sa.text("'discovered'"), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('google_place_id')
    )
    op.create_index('idx_leads_lead_score', 'leads', ['lead_score'], unique=False)
    op.create_index('idx_leads_qualified', 'leads', ['qualified'], unique=False)
    op.create_index('idx_leads_sector', 'leads', ['sector'], unique=False)
    op.create_index('idx_leads_service_type', 'leads', ['suggested_service_type'], unique=False)
    op.create_index('idx_leads_status', 'leads', ['status'], unique=False)
    op.create_table('clients',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('lead_id', sa.UUID(), nullable=True),
    sa.Column('business_name', sa.Text(), nullable=False),
    sa.Column('vat_number', sa.Text(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('city', sa.Text(), nullable=True),
    sa.Column('region', sa.Text(), nullable=True),
    sa.Column('country', sa.Text(), server_default=sa.text("'IT'"), nullable=True),
    sa.Column('contact_name', sa.Text(), nullable=True),
    sa.Column('contact_email', sa.Text(), nullable=True),
    sa.Column('contact_phone', sa.Text(), nullable=True),
    sa.Column('sla_response_hours', sa.Integer(), server_default=sa.text('4'), nullable=True),
    sa.Column('preferred_language', sa.Text(), server_default=sa.text("'it'"), nullable=True),
    sa.Column('timezone', sa.Text(), server_default=sa.text("'Europe/Rome'"), nullable=True),
    sa.Column('db_schema_name', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('db_schema_name')
    )
    op.create_table('deals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('lead_id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Text(), server_default=sa.text("'lead_identified'"), nullable=False),
    sa.Column('service_type', sa.Text(), nullable=False),
    sa.Column('sector', sa.Text(), nullable=False),
    sa.Column('estimated_value_eur', sa.Integer(), nullable=True),
    sa.Column('proposal_human_approved', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False),
    sa.Column('proposal_approved_at', sa.DateTime(), nullable=True),
    sa.Column('proposal_approved_by', sa.Text(), server_default=sa.text("'operator'"), nullable=True),
    sa.Column('proposal_rejection_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('proposal_rejection_notes', sa.Text(), nullable=True),
    sa.Column('kickoff_confirmed', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False),
    sa.Column('kickoff_confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('delivery_approved', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False),
    sa.Column('delivery_approved_at', sa.DateTime(), nullable=True),
    sa.Column('delivery_rejection_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('delivery_rejection_notes', sa.Text(), nullable=True),
    sa.Column('consulting_approved', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False),
    sa.Column('consulting_approved_at', sa.DateTime(), nullable=True),
    sa.Column('total_price_eur', sa.Integer(), nullable=True),
    sa.Column('deposit_pct', sa.Integer(), server_default=sa.text('30'), nullable=True),
    sa.Column('payment_terms_days', sa.Integer(), server_default=sa.text('30'), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('lost_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_deals_client_id', 'deals', ['client_id'], unique=False)
    op.create_index('idx_deals_lead_id', 'deals', ['lead_id'], unique=False)
    op.create_index('idx_deals_service_type', 'deals', ['service_type'], unique=False)
    op.create_index('idx_deals_status', 'deals', ['status'], unique=False)
    op.create_table('invoices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('deal_id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('invoice_number', sa.Text(), nullable=True),
    sa.Column('milestone', sa.Text(), nullable=False),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('tax_rate_pct', sa.Numeric(precision=4, scale=2), server_default=sa.text('22.00'), nullable=True),
    sa.Column('tax_cents', sa.Integer(), nullable=True),
    sa.Column('total_cents', sa.Integer(), nullable=True),
    sa.Column('status', sa.Text(), server_default=sa.text("'draft'"), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('payment_method', sa.Text(), nullable=True),
    sa.Column('billing_dispute', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False),
    sa.Column('billing_dispute_notes', sa.Text(), nullable=True),
    sa.Column('pdf_path', sa.Text(), nullable=True),
    sa.Column('reminder_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('last_reminder_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invoice_number')
    )
    op.create_index('idx_invoices_client_id', 'invoices', ['client_id'], unique=False)
    op.create_index('idx_invoices_deal_id', 'invoices', ['deal_id'], unique=False)
    op.create_index('idx_invoices_due_date', 'invoices', ['due_date'], unique=False)
    op.create_index('idx_invoices_status', 'invoices', ['status'], unique=False)
    op.create_table('nps_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('deal_id', sa.UUID(), nullable=True),
    sa.Column('trigger', sa.Text(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=False),
    sa.Column('responded_at', sa.DateTime(), nullable=True),
    sa.Column('followup_action', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_nps_client_id', 'nps_records', ['client_id'], unique=False)
    op.create_table('proposals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('deal_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('pdf_path', sa.Text(), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('gap_summary', sa.Text(), nullable=True),
    sa.Column('solution_summary', sa.Text(), nullable=True),
    sa.Column('service_type', sa.Text(), nullable=False),
    sa.Column('deliverables_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('pricing_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('timeline_weeks', sa.Integer(), nullable=True),
    sa.Column('roi_summary', sa.Text(), nullable=True),
    sa.Column('artifact_paths', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('portal_link_token', sa.Text(), nullable=True),
    sa.Column('portal_link_expires', sa.DateTime(), nullable=True),
    sa.Column('client_viewed_at', sa.DateTime(), nullable=True),
    sa.Column('client_response', sa.Text(), nullable=True),
    sa.Column('client_response_at', sa.DateTime(), nullable=True),
    sa.Column('client_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('deal_id', 'version', name='uq_proposals_deal_version')
    )
    op.create_index('idx_proposals_deal_id', 'proposals', ['deal_id'], unique=False)
    op.create_table('runs',
    sa.Column('run_id', sa.Text(), nullable=False),
    sa.Column('deal_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Text(), server_default=sa.text("'running'"), nullable=False),
    sa.Column('current_phase', sa.Text(), nullable=True),
    sa.Column('current_agent', sa.Text(), nullable=True),
    sa.Column('gate_type', sa.Text(), nullable=True),
    sa.Column('awaiting_gate_since', sa.DateTime(), nullable=True),
    sa.Column('started_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], ),
    sa.PrimaryKeyConstraint('run_id')
    )
    op.create_index('idx_runs_deal_id', 'runs', ['deal_id'], unique=False)
    op.create_index('idx_runs_status', 'runs', ['status'], unique=False)
    op.create_table('service_deliveries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('deal_id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('service_type', sa.Text(), nullable=False),
    sa.Column('type', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('milestone_name', sa.Text(), nullable=True),
    sa.Column('milestone_due', sa.Date(), nullable=True),
    sa.Column('depends_on', postgresql.ARRAY(sa.UUID()), nullable=True),
    sa.Column('artifact_paths', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('assigned_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('operator_approved', sa.Boolean(), nullable=True),
    sa.Column('operator_approved_at', sa.DateTime(), nullable=True),
    sa.Column('operator_notes', sa.Text(), nullable=True),
    sa.Column('rejection_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('rejection_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_svc_deliveries_client_id', 'service_deliveries', ['client_id'], unique=False)
    op.create_index('idx_svc_deliveries_deal_id', 'service_deliveries', ['deal_id'], unique=False)
    op.create_index('idx_svc_deliveries_service_type', 'service_deliveries', ['service_type'], unique=False)
    op.create_index('idx_svc_deliveries_status', 'service_deliveries', ['status'], unique=False)
    op.create_table('tasks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Text(), nullable=False),
    sa.Column('agent', sa.Text(), nullable=False),
    sa.Column('deal_id', sa.UUID(), nullable=True),
    sa.Column('client_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Text(), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('output', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('blocked_reason', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('idempotency_key', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_index('idx_tasks_agent', 'tasks', ['agent'], unique=False)
    op.create_index('idx_tasks_deal_id', 'tasks', ['deal_id'], unique=False)
    op.create_index('idx_tasks_idem_key', 'tasks', ['idempotency_key'], unique=False, postgresql_where=sa.text('idempotency_key IS NOT NULL'))
    op.create_index('idx_tasks_status', 'tasks', ['status'], unique=False)
    op.create_table('delivery_reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('service_delivery_id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('approved', sa.Boolean(), nullable=False),
    sa.Column('completeness_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('blocking_issues', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('notes', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('reviewer_agent', sa.Text(), nullable=False),
    sa.Column('report_path', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['service_delivery_id'], ['service_deliveries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_delivery_reports_svc_id', 'delivery_reports', ['service_delivery_id'], unique=False)
    op.create_table('email_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('deal_id', sa.UUID(), nullable=True),
    sa.Column('client_id', sa.UUID(), nullable=True),
    sa.Column('task_id', sa.UUID(), nullable=True),
    sa.Column('direction', sa.Text(), nullable=False),
    sa.Column('agent', sa.Text(), nullable=False),
    sa.Column('template_name', sa.Text(), nullable=True),
    sa.Column('gmail_message_id', sa.Text(), nullable=True),
    sa.Column('gmail_thread_id', sa.Text(), nullable=True),
    sa.Column('subject', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('opened_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_email_log_client_id', 'email_log', ['client_id'], unique=False)
    op.create_index('idx_email_log_deal_id', 'email_log', ['deal_id'], unique=False)
    op.create_index('idx_email_log_thread', 'email_log', ['gmail_thread_id'], unique=False)
    op.create_table('tickets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('deal_id', sa.UUID(), nullable=True),
    sa.Column('type', sa.Text(), nullable=True),
    sa.Column('severity', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), server_default=sa.text("'open'"), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('gmail_thread_id', sa.Text(), nullable=True),
    sa.Column('first_response_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('service_delivery_id', sa.UUID(), nullable=True),
    sa.Column('escalated', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False),
    sa.Column('escalated_at', sa.DateTime(), nullable=True),
    sa.Column('escalation_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], ),
    sa.ForeignKeyConstraint(['service_delivery_id'], ['service_deliveries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_tickets_client_id', 'tickets', ['client_id'], unique=False)
    op.create_index('idx_tickets_severity', 'tickets', ['severity'], unique=False)
    op.create_index('idx_tickets_status', 'tickets', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_tickets_status', table_name='tickets')
    op.drop_index('idx_tickets_severity', table_name='tickets')
    op.drop_index('idx_tickets_client_id', table_name='tickets')
    op.drop_table('tickets')
    op.drop_index('idx_email_log_thread', table_name='email_log')
    op.drop_index('idx_email_log_deal_id', table_name='email_log')
    op.drop_index('idx_email_log_client_id', table_name='email_log')
    op.drop_table('email_log')
    op.drop_index('idx_delivery_reports_svc_id', table_name='delivery_reports')
    op.drop_table('delivery_reports')
    op.drop_index('idx_tasks_status', table_name='tasks')
    op.drop_index('idx_tasks_idem_key', table_name='tasks', postgresql_where=sa.text('idempotency_key IS NOT NULL'))
    op.drop_index('idx_tasks_deal_id', table_name='tasks')
    op.drop_index('idx_tasks_agent', table_name='tasks')
    op.drop_table('tasks')
    op.drop_index('idx_svc_deliveries_status', table_name='service_deliveries')
    op.drop_index('idx_svc_deliveries_service_type', table_name='service_deliveries')
    op.drop_index('idx_svc_deliveries_deal_id', table_name='service_deliveries')
    op.drop_index('idx_svc_deliveries_client_id', table_name='service_deliveries')
    op.drop_table('service_deliveries')
    op.drop_index('idx_runs_status', table_name='runs')
    op.drop_index('idx_runs_deal_id', table_name='runs')
    op.drop_table('runs')
    op.drop_index('idx_proposals_deal_id', table_name='proposals')
    op.drop_table('proposals')
    op.drop_index('idx_nps_client_id', table_name='nps_records')
    op.drop_table('nps_records')
    op.drop_index('idx_invoices_status', table_name='invoices')
    op.drop_index('idx_invoices_due_date', table_name='invoices')
    op.drop_index('idx_invoices_deal_id', table_name='invoices')
    op.drop_index('idx_invoices_client_id', table_name='invoices')
    op.drop_table('invoices')
    op.drop_index('idx_deals_status', table_name='deals')
    op.drop_index('idx_deals_service_type', table_name='deals')
    op.drop_index('idx_deals_lead_id', table_name='deals')
    op.drop_index('idx_deals_client_id', table_name='deals')
    op.drop_table('deals')
    op.drop_table('clients')
    op.drop_index('idx_leads_status', table_name='leads')
    op.drop_index('idx_leads_service_type', table_name='leads')
    op.drop_index('idx_leads_sector', table_name='leads')
    op.drop_index('idx_leads_qualified', table_name='leads')
    op.drop_index('idx_leads_lead_score', table_name='leads')
    op.drop_table('leads')
    # ### end Alembic commands ###
    op.execute("DROP EXTENSION IF EXISTS vector")
